const express = require('express');
const authRoutes = require('./appRoutes/authRoutes');
const googleAuthRoutes = require('./appRoutes/googleAuthRoutes');
const restaurantRoutes = require('./appRoutes/restaurantRoutes');
const favoriteRoutes = require('./appRoutes/favoriteRoutes');
const reviewRoutes = require('./appRoutes/reviewRoutes');
const reservationRoutes = require('./appRoutes/reservationRoutes');
const reservationMessageRoutes = require('./appRoutes/reservationMessageRoutes');
const achievementRoutes = require('./appRoutes/achievementRoutes');
const pointsRoutes = require('./appRoutes/pointsRoutes');
const userSettingsRoutes = require('./appRoutes/userSettingsRoutes');
const userRoutes = require('./appRoutes/userRoutes');
const searchHistoryRoutes = require('./appRoutes/searchHistoryRoutes');
const trendingSearchesRoutes = require('./appRoutes/trendingSearchesRoutes');
const foodCategoryRoutes = require('./appRoutes/foodCategoryRoutes');
const searchRoutes = require('./appRoutes/searchRoutes');
const typeRoutes = require('./appRoutes/typeRoutes');
const blogRoutes = require('./appRoutes/blogRoutes');
const newsletterRoutes = require('./appRoutes/newsletterRoutes');
const adminRoutes = require('./appRoutes/adminRoutes');
const feedRoutes = require('./appRoutes/feedRoutes');
const restaurantDetailsRoutes = require('./appRoutes/restaurantDetailsRoutes');
const mailRoutes = require('./appRoutes/mailRoutes');
const visitValidationRoutes = require('./appRoutes/visitValidationRoutes');
const specialOfferRoutes = require('./appRoutes/specialOfferRoutes');
const couponRoutes = require('./appRoutes/couponRoutes');
const analyticsRoutes = require('./appRoutes/analyticsRoutes');
const pushNotificationRoutes = require('./appRoutes/pushNotificationRoutes');
const referralRoutes = require('./appRoutes/referralRoutes');
const aiRoutes = require('./appRoutes/aiRoutes');
const aiMenuSearch = require('./appRoutes/ai/menuSearchRoutes');
const receiptRoutes = require('./appRoutes/receiptRoutes');
const leaderboardCycleRoutes = require('./appRoutes/leaderboardCycleRoutes');
const followRoutes = require('./appRoutes/followRoutes');
const visitRoutes = require('./appRoutes/visitRoutes');
const mustVisitRoutes = require('./appRoutes/mustVisitRoutes');
const router = express.Router();

router.use(authRoutes);
router.use(googleAuthRoutes);
router.use(restaurantRoutes);
router.use(favoriteRoutes);
router.use(reviewRoutes);
router.use(reservationRoutes);
router.use(reservationMessageRoutes);
router.use(achievementRoutes);
router.use(pointsRoutes);
router.use(userSettingsRoutes);
router.use(userRoutes);
router.use(searchHistoryRoutes);
router.use(trendingSearchesRoutes);
router.use(foodCategoryRoutes);
router.use(searchRoutes);
router.use(typeRoutes);
router.use(blogRoutes);
router.use(newsletterRoutes);
router.use(adminRoutes);
router.use(feedRoutes);
router.use(restaurantDetailsRoutes);
router.use(mailRoutes);
router.use(visitValidationRoutes);
router.use(specialOfferRoutes);
router.use(couponRoutes);
router.use(analyticsRoutes);
router.use(pushNotificationRoutes);
router.use(referralRoutes);
router.use(aiRoutes);
router.use(aiMenuSearch);
router.use(receiptRoutes);
router.use(leaderboardCycleRoutes);
router.use(followRoutes);
router.use(visitRoutes);
router.use(mustVisitRoutes);

module.exports = router;
